### ISSUE TITLE
DB duplicating charging days

### ISSUE THREAD

**Issue by frankmchugh** [stakevrun/frontend#310] opened 2024-06-13 21:01 UTC
I deleted the old issue by accident. But check instance given by Steely in Vrun chat a few days ago

**Comment by xrchz** [comment] 2024-06-21 17:59
I haven't been able to find the right message - do you have a link to it?

**Comment by xrchz** [comment] 2024-06-21 18:52
Got it here: https://discord.com/channels/1216708060832075806/1216708061507616821/1249362834396025012

**Comment by xrchz** [comment] 2024-06-21 18:58
Notes to myself:
https://fee.xn--vrn-ioa.com/17000/0xe72EC6a6D5d99A615e1D712B269E611331783FC8/0xa01b3b4dca5336666b066768d847f58365e08411218e0f06ef35b7699eb33f7e76186e8c139b9df05aa503cfbdbf0cc7/charges -- this is the raw fee data for that duplicate charge issue
Looks like because of the stop and start on the same day, that day is included in two ranges (as the last day of one range, and the first day of the next)
I guess the fee server should do some merging in that case?
maybe merge the whole range into a single range?
yeah I think that's the right move

**Comment by xrchz** [comment] 2024-06-21 19:12
I think this is addressed by https://github.com/stakevrun/fee/commit/99ea4b7c1e5893436d01873d4ab4f9a4a70e94f0

**Comment by xrchz** [comment] 2024-06-22 08:56
Confirmed fixed here https://discord.com/channels/1216708060832075806/1216708061507616821/1253965199506145291

**Closed by xrchz** 2024-06-22 08:56 UTC
